### ISSUE TITLE
Having a ":" instead of "." in conduit receiver gives unclear error

### ISSUE THREAD

**Issue by maarten-ic** [multiscale/ymmsl-python#19]
The error indicates that the Reference is not valid, but it should also print what the provided string is so you can more easily find it in the input ymmsl.

Possibly related to #18

**Comment by LourensVeen** [comment]
Also, see #11. Kind of silly to see this again, we should fix this properly this time.

**Comment by LourensVeen** [comment]
Ah, no I think #18 is a different issue, that's about the location being wrong.

**Comment by LourensVeen** [comment]
Ah, but they're related in the sense that with the location being wrong, if at least it would print the broken string that would help to find the problem. So they should both be fixed, but fixing at least one of them would already really help.

**Comment by LourensVeen** [comment]
The above commit now includes the rejected string in the error message, and I have fixed #18 on the YAtiML side, so in the next release you should now get a clear description of which bit of the input is incorrect, and also where you can find it.

**Comment by LourensVeen** [comment]
Released with 0.13.1.
